{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c4f5b05d-37ef-4a7a-80c8-257ae4761b8d",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask, request, jsonify\n",
    "from google import genai\n",
    "from google.genai import types\n",
    "import os\n",
    "from flask_cors import CORS # Szükséges a böngésző biztonsági korlátai miatt\n",
    "\n",
    "# --- APP BEÁLLÍTÁSOK ---\n",
    "app = Flask(__name__)\n",
    "# A Frontend (weboldal) kommunikációjához engedélyezzük a CORS-t\n",
    "CORS(app) \n",
    "\n",
    "# --- GEMINI INICIALIZÁLÁS ---\n",
    "# A kulcsot automatikusan a Hostingeren beállított környezeti változóból veszi át!\n",
    "try:\n",
    "    client = genai.Client() \n",
    "except Exception as e:\n",
    "    # Hiba esetén, ha a kulcs nincs beállítva a szerveren, hibát dob.\n",
    "    print(f\"HIBA: Nem sikerült a Gemini klienst inicializálni: {e}\")\n",
    "\n",
    "\n",
    "# --- A CHATBOT MAGJA ---\n",
    "\n",
    "def search_valasz_generálása(kérdés):\n",
    "    \"\"\"\n",
    "    Meghívja a Gemini-t, a Google Search eszközzel rászűrve a weboldal tartalmára.\n",
    "    \"\"\"\n",
    "    \n",
    "    # Kérdést egészítünk ki a weboldal URL-jével a célzott kereséshez.\n",
    "    user_query = f\"{kérdés} site:smarted.smartonlineedu.com\"\n",
    "    \n",
    "    # A Prompt Mérnökség: meghatározzuk a chatbot szerepét.\n",
    "    system_prompt = (\n",
    "        \"Te egy segítőkész Turisztikai és Gyógyászati Információs Asszisztens vagy, \"\n",
    "        \"aki Hargita megye természeti kincseire specializálódott. \"\n",
    "        \"Kizárólag a Google Search eszköz segítségével talált információkra alapozva válaszolj. \"\n",
    "        \"Formázz szépen, használj listákat és emojikat. Ha a keresés nem ad eredményt, udvariasan közöld, hogy nem tudsz segíteni.\"\n",
    "    )\n",
    "    \n",
    "    response = client.models.generate_content(\n",
    "        model=\"gemini-2.5-flash\", \n",
    "        contents=user_query,\n",
    "        config=types.GenerateContentConfig(\n",
    "            system_instruction=system_prompt,\n",
    "            # A Google Search eszköz bekapcsolása\n",
    "            tools=[{\"google_search\": {}}] \n",
    "        )\n",
    "    )\n",
    "    \n",
    "    return response.text\n",
    "\n",
    "# --- API VÉGPONT: /chat ---\n",
    "\n",
    "@app.route('/chat', methods=['POST'])\n",
    "def chat_endpoint():\n",
    "    \"\"\"Fogadja a Frontend kérését és válaszol a Geminivel.\"\"\"\n",
    "    \n",
    "    data = request.get_json()\n",
    "    user_message = data.get('message', '')\n",
    "    \n",
    "    if not user_message:\n",
    "        return jsonify({\"response\": \"Kérlek, adj meg egy üzenetet.\"}), 400\n",
    "\n",
    "    try:\n",
    "        ai_response_text = search_valasz_generálása(user_message)\n",
    "        \n",
    "        # Válasz visszaküldése JSON formátumban\n",
    "        return jsonify({\"response\": ai_response_text})\n",
    "    \n",
    "    except Exception as e:\n",
    "        print(f\"Hiba történt az AI hívás során: {e}\") \n",
    "        return jsonify({\"response\": \"Sajnálom, átmeneti hiba történt a szerveren. Kérlek, ellenőrizd a Gemini API kulcsot.\"}), 500\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    # Ezt a részt a Hostinger nem fogja használni, csak helyi tesztelésre való.\n",
    "    app.run(port=5000)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
